global using EGHeals.Application.Extensions.Validators;
global using BuildingBlocks.CQRS;
global using FluentValidation;
global using BuildingBlocks.DataAccessAbstraction.UnitOfWork;
global using BuildingBlocks.DataAccessAbstraction.Repository;
global using EGHeals.Domain.Models;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Pagination;
global using BuildingBlocks.Responses;